site_name: OmniRobot
site_description: 'Documentation on design and deployment of OmniBot catkin package'
# site_author: 'Martin Donath'
# site_url: '127.0.0.1:8001/'


# Repository
repo_name: 'jvillagomez/omnibot_pkg'
repo_url: 'https://github.com/jvillagomez/omnibot_pkg'

# Copyright
copyright: 'Copyright &copy; 2018 PasqLab'

pages:
  # - Index: index.md
  - Overview: index.md
  - Getting Started: gettingStarted.md
  - System Architecture: systemArchitecture.md
  - Components: components.md
  - Code Base: codeBase.md
  - Serial Latency: serialLatency.md
  - Troubleshooting: troubleshooting.md
  - Project Slack Channel: projectSlackChannel.md

theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'Blue Grey'
    accent: 'Cyan'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/OmniRobot_wheelLogo.png'
    # icon: 'cloud'

markdown_extensions:
  - codehilite:
      linenums: true
