site_name: OmniRobot
site_description: 'Documentation on design and deployment of OmniBot catkin package'
site_author: 'Martin Donath'
site_url: 'https://squidfunk.github.io/mkdocs-material/'


# Repository
repo_name: 'jvillagomez/omnibot_pkg'
repo_url: 'https://github.com/jvillagomez/omnibot_pkg'

# Copyright
copyright: 'Copyright &copy; 2018 PasqLab'

pages:
  - Overview: overview.md
  - System Architecture: systemArchitecture.md
  - Getting Started: gettingStarted.md
  - Components: components.md
  - Code Base: codeBase.md
  - Troubleshooting: troubleshooting.md
  - Project Slack Channel: projectSlackChannel.md

theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'Blue Grey'
    accent: 'Cyan'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/OmniRobot_wheelLogo.png'
    # icon: 'cloud'
